name: Build project

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build Cook It Yourself WEBGL
    runs-on: ubuntu-latest
    steps:
      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          lfs: true
          submodules: true

      # Cache
      - uses: actions/cache@v2
        with:
          path: CookItYourself/Library
          key: CookItYourself/Library-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
          restore-keys: |
            CookItYourself/Library-

      # Test TBD
      #- name: Run tests
       # uses: game-ci/unity-test-runner@v2
       # env:
       #   UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
       # with:
       #   githubToken: ${{ secrets.GITHUB_TOKEN }}

      # Build
      - name: Build project
        uses: game-ci/unity-builder@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: WebGL
          projectPath: CookItYourself
      # Submodule update
      - name: submodule commit
        run: |
          git config --global user.name 'Git bot'
          git config --global user.email 'bot@noreply.github.com'
          cp -r build/WebGL/WebGL/* chopdemo/
          cd chopdemo
          git add .
          git commit -am 'autodeploy'
          git push origin HEAD:master
          cd ..
          git commit -am 'autodeploy'
          git push origin HEAD:master
          
        
      
      # Output
      # - uses: actions/upload-artifact@v2
      #  with:
      #    name: Build
      #    path: build
      # Output
      # - run: tree
